### ISSUE TITLE
Broker datapoints interface to retrieve metadata should include data type unit

### ISSUE THREAD

**Issue by mikehaller** [eclipse/kuksa.val.services#102]
The [data unit types of VSS ](https://covesa.github.io/vehicle_signal_specification/rule_set/data_entry/data_unit_types/) should be exposed via GetMetadata as well.

Eg when subscribing to "Vehicle.Speed", the value is in "km/h" as specified. Since the spec can be overriden, it's hard for generic tools ("VSS Browser") to know the specific data type unit, unless it is exposed via the metadata interface.

**Comment by erikbosch** [comment]
As this seems to concern databroker it should possibly be filed at https://github.com/eclipse/kuksa.val/issues instead.

@argerus - could you possibly give quick feedback. Is it Databroker that does not send unit to clients, or is clients that does not show it. No change in proto required I assume?

```
Test Client> getMetaData Vehicle.Speed
{
    "path": "Vehicle.Speed",
    "metadata": {
        "data_type": "FLOAT",
        "entry_type": "SENSOR",
        "description": "Vehicle speed."
    }
}

sdv.databroker.v1 > metadata Vehicle.Speed
[metadata]  OK  
Path          Entry type Data type
Vehicle.Speed Sensor     Float    

```

**Comment by erikbosch** [comment]
@mikehaller @argerus - do we consider this one still relevant? If so I could "migrate" it to kuksa.val, or the new kuksa-databroker repo when migration is finished.

**Comment by mikehaller** [comment]
Still relevant imo.

**Comment by erikbosch** [comment]
Replaced by https://github.com/eclipse/kuksa.val/issues/755
