### ISSUE TITLE
Needed content for release

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val.services#109]
We have not had any "real" releases for this repo in a long time, so I am trying to look on what better should be done. Looking at our latest release at https://github.com/eclipse/kuksa.val.services/releases/tag/v0.2.0 we have the following artifacts:

![image](https://github.com/eclipse/kuksa.val.services/assets/30996601/374e2299-42e8-4cab-a574-1f76d9927bfe)

That is:

- Some generic stuff (LICENSE and NOTICE)
- Seat binaries and seat documentation
- Hvac and Seat containers

Somewhat inconsistent, and now we also have mock service. Some questions:

- What artifacts do you need?
- Does it make sense to include binaries for all services (seat, hvac, mock?) For both amd64 and aarch64?
- Do we need to have OCI-containers as part of the release if they anyway are available at ghcr (see https://github.com/orgs/eclipse/packages?repo_name=kuksa.val.services)?

My idea is to refactor this one so it:

- Does not upload or include ghcr images, upload can happen directly from lower level workflows. But the release may trigger those lower level workflows so that a release only is created if they succeed.
- Always use tag as version, i.e. it should not be possible to specify tag manually?

Opinions?

**Comment by SebastianSchildt** [comment]
So at least container images I would only make available via ghcr, those exported tar balls are not easy to handle anyway. I do think this still comes from a time when it wasn't easy/obvious how to push to a container registry

**Comment by SebastianSchildt** [comment]
It would also be good to have a mock image pushed, but I am not sure how feasible that is. If there is already scripting for that, whoch we just "need to connect to an action" , we should go for it, but if it involve more work, postpone it. I know @eriksven  is interested in a pullable mock container  for an upcoming bluprint :D

**Comment by erikbosch** [comment]
> It would also be good to have a mock image pushed, but I am not sure how feasible that is. If there is already scripting for that, whoch we just "need to connect to an action" , we should go for it, but if it involve more work, postpone it. I know @eriksven is interested in a pullable mock container for an upcoming bluprint :D

For the mock service, sending a container imageto ghcr on every merge to main (and ato ttls.h on each pull reques)t should be easy, and we seem to agree to NOT have any container images as the release artifact.

But then comes the question on binaries. Today, for seat service we build debug and release versions for both amd64 and arm64 for every pull request, and we include the release tarballs in the release. For hvac and mock we do not build natively, we just build for docker. Is there a reason to have a difference? The most simple solution would be to just skip the binaries also for seat service, but for kuksa.val we release databroker and databroker-cli as tarballs. So do we want amd64+arm64 tarballs also for hvac and mock service? But if we want to include only release-version in releases, is there still a reason to build a debug-version of seat-service on every pull request? Should be build debug-versions also for hvac and mock?

**Comment by int0x27** [comment]
- I don't think we have a seat service binary user at the moment, but they were provided for easier standalone testing
- there are no binaries for python services, e.g. in integration tests I just clone the repo/tag and use them directly
- seat service documentation could be removed
- multi-arch tar image files are not needed, they were used mainly on demo setups a long time ago (e.g. no ghcr access).

**Comment by erikbosch** [comment]
What I did for now:

- A pre-release created at https://github.com/eclipse/kuksa.val.services/releases/tag/v0.3.0
- Docker containers removed, but no other changes

@SebastianSchildt @int0x27 - please check the pre-release, if it contain what you expect.

@SebastianSchildt - if OK could you approval process

**Comment by erikbosch** [comment]
Considering this one completed, wiki at https://github.com/eclipse/kuksa.val.services/wiki/Release-Process updated
