### ISSUE TITLE
Bug in Dockerfile for mock service

### ISSUE THREAD

**Issue by PratikGaner** [eclipse/kuksa.val.services#115]
CMD arguments in the dockerfile not detecting mockservice.py since it is present in another folder "mock" which is in the same level as Dockerfile.

**Comment by vasilvas99** [comment]
Confirmed +1: 

This commit has moved files under the mockservice directory: https://github.com/eclipse/kuksa.val.services/commit/a1bff339cf03e9206115cb9bb9ae6afc3e4451f1

But the dockerfile is still referencing the old structure in the entrypoint:
https://github.com/eclipse/kuksa.val.services/blob/main/mock_service/Dockerfile

**Comment by PratikGaner** [comment]
when can the changes be updated?

**Comment by lukasmittag** [comment]
updated
