### ISSUE TITLE
Support ARM64 for dev container

### ISSUE THREAD

**Issue by doosuu** [eclipse/kuksa.val.services#68]
Problem:

The current dev container for the project is only available for x86_64 which forces arm64 users to run the dev container via QEMU. As expected this is very slow and dapr does not work from within docker-in-docker in a QEMU environment.

**Comment by erikbosch** [comment]
Has this been solved by #74?

**Comment by erikbosch** [comment]
Closing this one as we right now do not publish any devcontainer to ghcr. If this is still relevant we should better create new issues for the repos/components concerned, and what should be included in those devcontainers
