### ISSUE TITLE
Mockservice - dapr installation

### ISSUE THREAD

**Issue by antaradey-itk** [eclipse/kuksa.val.services#90]
**Objective**: To launch mockservice for controlling actuators and sensors.

**Issue**:
run-mockservice script is failing at dapr cli installation. Please take a look at the attached the log file. I am using Debian 12.0.

[dapr_insfail.txt](https://github.com/eclipse/kuksa.val.services/files/12356883/dapr_insfail.txt)

#######################################################
#######################################################
- Detected x86_64 architecture

Installing dapr latest version: v1.11.0
Getting the latest Dapr CLI...
Your system is linux_amd64
Installing Dapr CLI...

Installing v1.11.0 Dapr CLI...
Downloading https://github.com/dapr/cli/releases/download/v1.11.0/dapr_linux_amd64.tar.gz ...
Failed to install dapr
Failed to install Dapr CLI
For support, go to https://dapr.io

**Query**: Is there any container image for mockservice?

**Comment by MP91** [comment]
Hey @antaradey-itk  unfortunately the mock-service is not yet completely available at the eclipse repo. For now you find the container here: https://github.com/boschglobal/kuksa.val.services/pkgs/container/kuksa.val.services%2Fmock_service

**Comment by int0x27** [comment]
It seems a generic problem in vscode task: https://github.com/eclipse/kuksa.val.services/blob/main/.vscode/scripts/ensure-dapr.sh
If you want to use vscode tasks this should be handled.
Can you provide the output of manually starting the script from repo dir:
```
bash -x ./.vscode/scripts/ensure-dapr.sh 
```

**Comment by antaradey-itk** [comment]
Closing this issue as of now. 

Took a different approach to running mockservice:
1. Import mockservice from KUKSA to Velocitas
2. Run mockservice/customise with vehicle app.
3. Create docker container manually and deploy it to private registry.
